# https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run 
 
 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/sudokuscanner:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'eu.gcr.io/$PROJECT_ID/sudokuscanner:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'sudokuscanner'
   - '--image'
   - 'eu.gcr.io/$PROJECT_ID/sudokuscanner:$COMMIT_SHA'
   - '--region'
   - 'europe-west2'
   - '--platform'
   - 'managed'
 images:
 - 'eu.gcr.io/$PROJECT_ID/sudokuscanner:$COMMIT_SHA'